---
title: "01_load"
author: "Group12"
format: html
editor: visual
---

# Clear Environment

```{r}
# | echo: true
# | eval: true

rm(list = ls())
```

# Load libraries

```{r}
# | echo: true
# | eval: true

# Loading relevant packages used in the project
library(tidyverse)
library(patchwork)
library(dplyr)
library(readxl)
library(readr)

```

## Load data

```{r}
# | echo: true
# | eval: true

dir.create(path = "data/_raw", recursive = TRUE)

# Define the path to the Excel file
path_to_xlsx_file <- "data/_raw/PCOS_data_without_infertility.xlsx"

# List all sheet names to see which sheet to load
sheet_names <- excel_sheets(path_to_xlsx_file)
print(sheet_names)

# Load a specific sheet by name
<<<<<<< HEAD
PCOS_data_xlsx <- read_excel(path_to_xlsx_file, sheet = "Full_new")
print(head(PCOS_data_xlsx))  # View the first few rows

```

#### Write to TSV

```{r}
# Define the output path for the TSV file
path_to_tsv_file <- "data/_raw/PCOS_data_without_infertility.tsv"

# Read the desired sheet from the Excel file
PCOS_data_tsv <- read_excel(path_to_xlsx_file, sheet = "Full_new")

# Save the data as a TSV file
write.table(PCOS_data_tsv, file = path_to_tsv_file, sep = "\t", row.names = FALSE, quote = FALSE)

# Print the path to confirm
print(paste("TSV file saved at:", path_to_tsv_file))


=======
data_new <- read_excel(path_to_file, sheet = "Full_new")
print(head(data_new))
>>>>>>> 142b405f5576802aa3d0e4f4f7764b24f27c3f4f
```
