---
title: "01_load"
author: "Group12"
format: html
editor: visual
---

# Clear Environment

```{r}
# | echo: true
# | eval: true

rm(list = ls())
```

# Load libraries

```{r}
# | echo: true
# | eval: true

# Loading relevant packages used in this section

library(tidyverse)
library(readxl)
library(readr)

```

## Load data

```{r}
# | echo: true
# | eval: true

# Define path to the Excel file
path_to_xlsx_file <- "../data/_raw/PCOS_data_without_infertility.xlsx"

# List sheet names from the excel file
sheet_names <- excel_sheets(path_to_xlsx_file)
print(sheet_names)

# Load the file of interest by sheet name in the file
PCOS_data_xlsx <- read_excel(path_to_xlsx_file, sheet = "Full_new")

### Quality check
print(head(PCOS_data_xlsx))
print(paste("Xlsx file saved at:", path_to_xlsx_file))

```

#### Write and save to TSV

```{r}
# | echo: true
# | eval: true

# Define and create output path
path_to_tsv_file <- "../data/PCOS_data_without_infertility.tsv"

# Read the sheet of interest by sheet name
PCOS_data_tsv <- read_excel(path_to_xlsx_file, sheet = "Full_new")

# Save the data to TSV format
write.table(PCOS_data_tsv, file = path_to_tsv_file, sep = "\t", row.names = FALSE, quote = FALSE)

### Quality check
print(paste("TSV file saved at:", path_to_tsv_file))
```
