---
title: "04_describe"
author: "Group12"
format: html
editor: visual
---

## Clear environment

```{r}
# | echo: true
# | eval: true

rm(list = ls())
```

## Load libraries

```{r}
# | echo: true
# | eval: true

# load libraries
library("tidyverse")
library(RColorBrewer)
library(ggplot2)
library(ggridges)
```

## Load data

```{r}
# | echo: true
# | eval: true

#Load the file
body_measurements <- read_tsv(file = "../data/PCOS_body_measurements_aug.tsv")
blood_measurements <- read_tsv(file = "../data/PCOS_blood_measurements_aug.tsv")
PCOS <- read_tsv(file = "../data/PCOS_merged.tsv")

```

## Data statistics

Checking dimensions of metadata

```{r}
# | echo: true
# | eval: true

# cheking the dimensions of the body measurements
body_measurements_dim <- body_measurements |>
  dim() |>
  tibble()|>
  rename("Body measurments dimensions" = "dim(body_measurements)")|>
  print()

# cheking the dimensions of the blood measurements
blood_measurements_dim <- blood_measurements |>
  dim() |>
  tibble()|>
  rename("Blood measurments dimensions" = "dim(blood_measurements)")|>
  print()
  
# cheking the dimensions of the blood measurements
PCOS_dim <- PCOS |>
  dim() |>
  tibble()|>
  rename("PCOS dimensions" = "dim(PCOS)")|>
  print()


```

Checking column names and patients with and without PCOS diagnosis

```{r}
# | echo: true
# | eval: true

# which column names exist in the merged data set:
PCOS |> 
  colnames()

# counting patients with (yes) and without (no PCOS diagnosis)
PCOS |> 
  count(PCOS_diagnosis)


```

There are 364 patients who have not been diagnosed with PCOS and 177 who have been diagnosed with PCOS.

## Plotting distributions of data

```{r}
# | echo: true
# | eval: true

body_measurements |>
  ggplot(mapping = aes(x=period_length, fill = PCOS_diagnosis)) + 
  geom_density(alpha = 0.45)+
  labs(x = "Period length (days)", 
       y = "Density",
       title = "Density plot of period lengths",
       fill = "PCOS diagnosis")

```

```{r}
# | echo: true
# | eval: true

# Age distribution



```

```{r}
# | echo: true
# | eval: true

# Creating bar chart of BMI distribution stratified on PCOS diagnosis
BMI_bar <- body_measurements |> 
  ggplot(mapping = aes(x = BMI_class,
                       fill = PCOS_diagnosis)) +
  geom_bar(position = position_dodge(preserve = "single"),
           alpha = 0.45,
           color = "black") +
  labs(x = "BMI groups", 
       y = "Count",
       title = "Barchart over BMI groups stratified PCOS diagnosis",
       fill = "PCOS diagnosis")

# Saving the plot as a picture
ggsave(BMI_bar,
       filename = "../results/04_BMI_bar.png",
       device = "png",
       height = 20,
       width = 20,
       units = "cm")

```

```{r}
# | echo: true
# | eval: true

# Creating barplot of blood types present in the dataset
blood_type_plot <- body_measurements |> 
  ggplot(mapping = aes(x = blood_type, 
                       fill = PCOS_diagnosis)) +
  geom_bar(position = position_dodge(preserve = "single"),
           alpha = 0.45,
           color = "black") +
  labs(x = "Blood type", 
       y = "Count",
       title = "Barchart of blood groups stratified for PCOS diagnosis",
       fill = "PCOS diagnosis")

# QC
print(blood_type_plot)

# Saving the plot as a picture

ggsave(blood_type_plot,
       filename = "../results/04_Blood_type_bar.png",
       device = "png",
       height = 20,
       width = 20,
       units = "cm")

```

## 
