---
title: "05_analysis_1"
author: "Group12"
format: html
editor: visual
---

## Clear environment

```{r}
# | echo: true
# | eval: true

rm(list = ls())
```

## Load libraries

```{r}
# | echo: true
# | eval: true

# load libraries
library("tidyverse")
library(patchwork)
library(RColorBrewer)
library(ggplot2)
library(ggridges)
library(RColorBrewer)

```

## Load data

```{r}
# | echo: true
# | eval: true

# Loading file
body_measurements <- read_tsv(file = "../data/PCOS_body_measurements_aug.tsv")

```

# Metadata analysis

First part of this project, is to see if there is a correlation between patients with PCOS using the metadata.

## Follicle and PCOS

```{r}
# | echo: true
# | eval: true


# Distribution of follicles in both ovaries with trend lines
p_follicles_ovaries <- body_measurements |> 
  ggplot(mapping = aes(x = follicle_no_R,
                       y = follicle_no_L,
                       color = PCOS_diagnosis)) + 
  geom_point() +  
  geom_smooth(method = "lm", 
              se = TRUE, 
              aes(fill = PCOS_diagnosis), 
              alpha = 0.3) + 
  scale_color_manual(values = c("Yes" = "Turquoise", 
                               "No" = "orchid")) + 
  scale_fill_manual(values = c("Yes" = "Turquoise", 
                               "No" = "orchid")) + 
  labs(title = "Distribution of follicles in both ovaries",
       x = "Follicle No. (R)", 
       y = "Follicle No. (L)",
       color = "PCOS Diagnosis",
       fill = "PCOS Diagnosis") +
  theme_minimal() + 
  theme(legend.position = "bottom")

# Saving the plot as a picture
ggsave(p_follicles_ovaries,
       filename = "../results/05_follicle_correlation.png",
       device = "png",
       height = 20,
       width = 20,
       units = "cm")

```

```{r}

# | echo: true
# | eval: true


p_follicle_L <- body_measurements |> 
  ggplot(aes(x = PCOS_diagnosis, 
             y = follicle_no_L)) + 
  geom_boxplot(aes(fill = PCOS_diagnosis), 
               outlier.shape = NA, 
               alpha = 0.5) + 
  geom_jitter(width = 0.2, 
              alpha = 0.8, 
              size = 1) + 
  scale_fill_manual(values = c("Yes" = "Turquoise", 
                               "No" = "orchid")) + 
  labs(x = "PCOS (Y/N)", 
       y = "Follicle No. (L)") + 
  theme_minimal()

ggsave(p_follicles_L,
       filename = "../results/05_follicle_L_box.png",
       device = "png",
       height = 20,
       width = 20,
       units = "cm")


p2 <- body_measurements |> 
  ggplot(aes(x = PCOS_diagnosis, 
             y = follicle_no_R)) + 
  geom_boxplot(aes(fill = PCOS_diagnosis), 
               outlier.shape = NA, 
               alpha = 0.5) + 
  geom_jitter(width = 0.2, 
              alpha = 0.8, 
              size = 1) + 
  scale_fill_manual(values = c("Yes" = "Turquoise", 
                               "No" = "orchid")) + 
  labs(x = "PCOS (Y/N)", 
       y = "Follicle No. (R)") + 
  theme_minimal()

# saving the 
ggsave(p_follicles_L,
       filename = "../results/05_follicle_L_box.png",
       device = "png",
       height = 20,
       width = 20,
       units = "cm")
```

## Correlation between BMI and PCOS

```{r}
PCOS_BMI_correlation_box <- body_measurements |> 
  ggplot(mapping = aes(x = PCOS_diagnosis,
                       y = BMI,
                       fill = PCOS_diagnosis)) +
  geom_boxplot() +
  geom_jitter(alpha = 0.20) +
  labs(x = "PCOS diagnosis", 
       y = "BMI",
       title = "Correlation between BMI and PCOS diagnosis",
       fill = "PCOS diagnosis")+
  scale_fill_brewer(palette="Set3")+
  theme_light()

# Saving the plot as a picture
ggsave(PCOS_BMI_correlation_box,
       filename = "../results/05_PCOS_BMI_correlation_box.png",
       device = "png",
       height = 20,
       width = 20,
       units = "cm")


```

## Correlation between PCOS and endometrium size

```{r}
PCOS_endometrium_correlation_box <- body_measurements |> 
  ggplot(mapping = aes(x = PCOS_diagnosis,
                       y = endometrium,
                       fill = PCOS_diagnosis)) +
  geom_boxplot() +
  geom_jitter(alpha = 0.20) +
  labs(x = "PCOS diagnosis", 
       y = "Endometrium size (mm)",
       title = "Correlation between endometrium size and PCOS diagnosis",
       fill = "PCOS diagnosis")+
  scale_fill_brewer(palette="Set3")+
  theme_light()

# Saving the plot as a picture
ggsave(PCOS_endometrium_correlation_box,
       filename = "../results/05_PCOS_endometrium_correlation_box.png",
       device = "png",
       height = 20,
       width = 20,
       units = "cm")

```

## Header if needed 1

```{r}
# | echo: true
# | eval: true

#Age vs. cycle stratified for PCOS diagnosis
age_cycle_plot <- na.omit(body_measurements) |> 
  ggplot(mapping = aes(x = age,
                       y = cycle_RI,
                       color = PCOS_diagnosis)) +
  geom_point() +
  labs(x = "Age", 
       y = "Cycle (Irregular / Regular)",
       title = "Correlation between age and cycle",
       color = "PCOS diagnosis")+
  scale_color_brewer(palette="Set3")+
  theme_light()

print(age_cycle_plot)

```

## Header if needed 2

```{r}
# | echo: true
# | eval: true


# age mod hair growth stratisfied for PCOS

p_age_hair <- body_measurements |> 
  ggplot(mapping = aes(x = age_group,
                       y = hair_growth,
                       color = PCOS_diagnosis)) +
  geom_point() +
  geom_jitter(width = 0.2, 
              alpha = 0.8, 
              size = 1) 

p_age_hair
```

## Header if needed 3

```{r}
# | echo: true
# | eval: true




```

## Header if needed 4

```{r}
# | echo: true
# | eval: true


```
