---
title: "06_analysis_2"
author: "Group12"
format: html
editor: visual
---

## 

## Clear environment

```{r}
# | echo: true 
# | eval: true 

rm(list = ls())
```

## Load libraries

```{r}
# | echo: true 
# | eval: true

library("tidyverse")
library(reshape2)
```

## Load data

```{r}
# | echo: true 
# | eval: true  

blood_measurements <- read_tsv(file = "../data/PCOS_blood_measurements_aug.tsv") 
```

# Blood data analysis

First part of this project, is to see if there is a correlation between patients with PCOS using the data from the blood samples.

## header for plots

```{r}
box_AMH <- blood_measurements |> 
  ggplot(mapping = aes(x = PCOS_diagnosis,
                       y = AMH,
                       fill = PCOS_diagnosis)) + 
  geom_boxplot(outliers = FALSE)+
  labs(x = "PCOS diagnosis", 
       y = "AMH level",
       title = "Boxplot of AMH level and PCOS diagnosis",
       fill = "PCOS diagnosis")+
  scale_fill_brewer(palette = "Set3")+
  theme_light()


# Saving the plot as a picture
ggsave(box_AMH,
       filename = "../results/06_box_AMH.png",
       device = "png",
       height = 20,
       width = 20,
       units = "cm")
```

## header for flere plots

```{r}
# | echo: true 
# | eval: true  

blood_measurements |> 
  ggplot(mapping = aes(x = PCOS_diagnosis, y=FSH_LH_ratio)) + 
  geom_point(alpha = 0.90)+
  labs(x = "Period length (days)", 
       y = "Density",
       title = "Density plot of period lengths",
       fill = "PCOS diagnosis")+
  theme_light()

blood_measurements |> 
  ggplot(mapping = aes(x = PCOS_diagnosis, y=PRL, fill = PCOS_diagnosis)) + 
  geom_violin(alpha = 0.90)+
  geom_point(position = "jitter")+
  labs(x = "PCOS diagnosis (", 
       y = "Density",
       title = "Density of PCOS patients with PRL values",
       fill = "PCOS diagnosis")+
  theme_light()


```

## Header for endnu flere plots

```{r}
# | echo: true 
# | eval: true  


hormones <- c("FSH", "LH", "FSH_LH_ratio", "TSH", "AMH", "PRL", "vitaminD3", "PRG", "RBS")

blood_measurements[hormones] <- lapply(blood_measurements[hormones], as.numeric)

blood_measurements$PCOS_diagnosis <- ifelse(blood_measurements$PCOS_diagnosis == "Yes", 1, 0)

cor_matrix <- cor(blood_measurements[hormones], blood_measurements$PCOS_diagnosis)

cor_long <- melt(cor_matrix)


ggplot(cor_long, aes(x = Var1, y = Var2, fill = value)) +
  geom_tile() +
  scale_fill_gradient2(low = "blue", mid = "white", high = "red", midpoint = 0) +
  labs(title = "Correlation Heatmap: Hormones and PCOS Diagnosis",
       x = "Hormones", y = "PCOS Diagnosis") +
  theme_minimal()

```

## header for sygt mange plots

```{r}
library(tidyverse)
library(corrr)

# Make a correlation table of the variables
cor_table <- blood_measurements |>  
  select(hemaglobin, betaHCG_1, betaHCG_2, FSH, LH, TSH, AMH, PRL, vitaminD3, PRG, RBS)|> 
  correlate(diagonal = 1)

melted_table <- cor_table |> 
  pivot_longer(-term, names_to = "variable", values_to = "value")

# Order the axis
melted_table <- melted_table |> 
  mutate(
    term = factor(term, levels = cor_table$term),
    variable = factor(variable, levels = cor_table$term)
  )


cor_blood_plot <- ggplot(data = melted_table, 
       mapping = aes(x = term, 
                     y = variable, 
                     fill = value)) + 
  geom_tile() +
  scale_y_discrete(limits = rev(levels(melted_table$variable))) +
  theme_minimal() + 
 theme(axis.text.x = element_text(angle = 45, 
                                  vjust = 1, 
                                  size = 9, 
                                  hjust = 1))+
 coord_fixed()+
  scale_fill_gradient2(low = "blue", 
                       high = "red", 
                       mid = "white", 
                       midpoint = 0, 
                       limit = c(-1,1), 
                       space = "Lab")+
  labs(x = "", 
       y = "", 
       fill = "Correlation",
       title = "Correlationplot of the blood values")+
  theme(title = element_text(size = 12))

ggsave(cor_blood_plot,
       filename = "../results/06_cor_blood_plot.png",
       device = "png",
       height = 20,
       width = 20,
       units = "cm")
```
